// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.API;

#nullable disable

namespace PMS.API.Migrations
{
    [DbContext(typeof(PMSDbContext))]
    [Migration("20260223032226_AddProductData")]
    partial class AddProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderPaintProduct", b =>
                {
                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<int>("PaintProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersOrderId", "PaintProductsId");

                    b.HasIndex("PaintProductsId");

                    b.ToTable("OrderPaintProduct");
                });

            modelBuilder.Entity("PMS.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PMS.Models.PaintProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DuluxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaintProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PaintSeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaintSeriesId");

                    b.ToTable("PaintProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is product 1",
                            DuluxId = new Guid("750a5333-344e-41f9-aacb-07f2bc0c24e7"),
                            PaintProductName = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is product 2",
                            DuluxId = new Guid("5d613d58-23e2-45ec-a906-89465f224d2a"),
                            PaintProductName = "Product 2"
                        });
                });

            modelBuilder.Entity("PMS.Models.PaintSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintSeries");
                });

            modelBuilder.Entity("OrderPaintProduct", b =>
                {
                    b.HasOne("PMS.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.PaintProduct", null)
                        .WithMany()
                        .HasForeignKey("PaintProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PMS.Models.PaintProduct", b =>
                {
                    b.HasOne("PMS.Models.PaintSeries", null)
                        .WithMany("PaintProducts")
                        .HasForeignKey("PaintSeriesId");
                });

            modelBuilder.Entity("PMS.Models.PaintSeries", b =>
                {
                    b.Navigation("PaintProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
